# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "vmd" "xhci_pci" "thunderbolt" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/3eb50103-1a8d-484b-bcba-745f25883175";
      fsType = "f2fs";
    };

  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/b7a83494-aaed-4f87-bcde-2de401cd0a5d";
      fsType = "f2fs";
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/46307b9e-7391-406f-bb5c-fde9af8aabc8";
      fsType = "f2fs";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/4c3090c8-e885-4f51-a556-381dfe385e67";
      fsType = "f2fs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/80e6f8d2-fa1f-4941-8d7b-695b5d92521e";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."boot_crypt".device = "/dev/disk/by-uuid/1a8b9414-bac2-4c99-9611-0f4d8044d1f4";

  fileSystems."/boot/EFI" =
    { device = "/dev/disk/by-uuid/4B26-AC94";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/bc4b58b3-5d86-484b-a54a-5ed1250dc26f"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
