{
  system,
  pkgs,
  rust-overlay,
  dotacatFast
}:
let
  wrapped-portal = pkgs.writeShellScriptBin "xdg-desktop-portal-cosmic-wrapper" ''
    export WAYLAND_DISPLAY=$(ls /run/user/$UID | grep -E '^wayland-[0-9]+$' | head -n1)
    export XDG_SESSION_TYPE=wayland
    export XDG_CURRENT_DESKTOP=cosmic
    exec ${pkgs.xdg-desktop-portal-cosmic}/libexec/xdg-desktop-portal-cosmic
  '';
in {
    myPkgs = with pkgs; [
        wrapped-portal

        (rust-bin.nightly.latest.default.override {
          targets = [ "wasm32-unknown-unknown" ];
          extensions = [ "rust-src" "rust-analyzer" ];
        })
        (vscode-with-extensions.override {
          vscodeExtensions = with vscode-extensions; [
            bbenoist.nix
            ms-azuretools.vscode-docker
            dhall.vscode-dhall-lsp-server
            dhall.dhall-lang
          ];
        })
        (lib.hiPrio xwayland)
        # android-tools
        # android-udev-rules
        atkmm
        at-spi2-atk
        atuin
        babelfish
        bandwhich
        bat
        bonnie
        bottles
        bottom
        btop
        buildkit
        cachix
        cairo
        cargo-generate
        cargo-leptos
        cargo-tauri
        cheese
        clamav
        clang_20
        clangStdenv
        cl-wordle
        cni-plugins
        containerd
        cosmic-bg
        cosmic-osd
        cosmic-term
        cosmic-idle
        cosmic-edit
        cosmic-comp
        cosmic-store
        cosmic-randr
        cosmic-panel
        cosmic-icons
        cosmic-files
        cosmic-player
        cosmic-session
        cosmic-greeter
        cosmic-ext-ctl
        cosmic-applets
        cosmic-settings
        cosmic-launcher
        cosmic-protocols
        cosmic-wallpapers
        cosmic-screenshot
        cosmic-ext-tweaks
        cosmic-applibrary
        cosmic-design-demo
        cosmic-notifications
        cosmic-ext-calculator
        cosmic-settings-daemon
        cosmic-workspaces-epoch
        xdg-desktop-portal-cosmic
        cowsay
        cri-o
        cryptsetup
        cups
        deja-dup
        delta
        dhall
        dhall-bash
        dhall-docs
        dhall-json
        dhall-lsp-server
        dhall-nix
        dhall-nixpkgs
        dhallPackages.dhall-kubernetes
        dhallPackages.Prelude
        dhall-yaml
        direnv
        distrobox
        doas
        docker
        dosfstools
        dotacatFast.packages.${system}.default
        dust
        e2fsprogs
        efibootmgr
        efitools
        efivar
        ente-desktop
        esbuild
        #expressvpn
        eza
        fd
        ffmpeg_8-full
        file
        findutils
        firmware-updater
        fish
        fishPlugins.bass.src
        fishPlugins.foreign-env.src
        fishPlugins.grc.src
        fortune
        furmark
        fwupd-efi
        fzf
        gdk-pixbuf
        gh
        gitFull
        git-cliff
        git-filter-repo
        glib
        glmark2
        mesa-demos
        gobject-introspection
        graphviz
        grc
        grex
        grub2_efi
        gst_all_1.gstreamer
        gtk3
        gtkimageview
        gucharmap
        harfbuzz
        haskellPackages.dhall-openapi
        haskellPackages.dhall-toml
        haskellPackages.dhall-yaml
        hunspell
        hunspellDicts.en-us
        hyperfine
        intel-gpu-tools
        jdk
        jq
        jqp
        kernel-hardening-checker
        kind
        kitty
        kitty-img
        kitty-themes
        kompose
        kubectl
        kubernetes-helm
        libcanberra-gtk3
        libreoffice-fresh
        librewolf
        librsvg
        libsoup_3
        lld_20
        llvmPackages_20.clangUseLLVM
        lshw
        lsof
        lvm2
        maven
        mdadm
        mdcat
        microsoft-edge
        monero-gui
        monero-cli
        mullvad-vpn
        mullvad-closest
        neofetch
        nerdctl
        nerd-fonts.fira-code
        nerd-fonts.fira-mono
        networkmanager-iodine
        networkmanager-openvpn
        networkmanager-vpnc
        nftables
        nixd
        nix-index
        nix-prefetch-git
        nodejs
        neovim
        #nvim-pkg
        nvme-cli
        nvtopPackages.intel
        ollama-cuda
        openssl
        openssl.dev
        pandoc
        pango
        parted
        patool
        pciutils
        pineapple-pictures
        pkg-config
        plocate
        podman
        podman-compose
        podman-desktop
        protonvpn-gui
        psmisc
        pwgen
        # qmk
        ripgrep
        ripgrep-all
        rootlesskit
        seahorse
        signal-desktop
        simple-scan
        slirp4netns
        sqlite
        starship
        sysstat
        tailwindcss
        tealdeer
        tinyxxd
        tldr
        tmux
        tree
        tree-sitter
        trunk
        unzip
        usbutils
        uv
        viu
        #vkmark
        vulkan-tools
        vulnix
        #wasm-bindgen-cli_0_2_100
        #wasmer
        #wasmer-pack
        #wasm-pack
        #wasmtime
        wayland-utils
        webkitgtk_4_1
        weston
        wget
        wine64
        winetricks
        wineWowPackages.staging
        wineWowPackages.waylandFull
        wireguard-tools
        wl-clipboard-rs
        wordbook
        xbindkeys
        xbindkeys-config
        yaru-theme
        zed-editor
        zellij
        zoom-us
    ];

    wrapped-portal = wrapped-portal;
}
