{
  system,
  pkgs,
  rust-overlay,
  dotacatFast
}:
let
  wrapped-portal = pkgs.writeShellScriptBin "xdg-desktop-portal-cosmic-wrapper" ''
    export WAYLAND_DISPLAY=$(ls /run/user/$UID | grep -E '^wayland-[0-9]+$' | head -n1)
    export XDG_SESSION_TYPE=wayland
    export XDG_CURRENT_DESKTOP=cosmic
    exec ${pkgs.xdg-desktop-portal-cosmic}/libexec/xdg-desktop-portal-cosmic
  '';
in {
    myPkgs = with pkgs; [
        wrapped-portal
        (rust-bin.nightly.latest.default.override {
          targets = [ "wasm32-unknown-unknown" ];
          extensions = [ "rust-src" "rust-analyzer" "miri" ];
        })
        atkmm
        at-spi2-atk
        atuin
        babelfish
        bandwhich
        bat
        bonnie
        (bottles.override { removeWarningPopup = true; })   # a wine prefix UI
        bottom
        btop
        buildkit
        cachix
        cairo
        cargo-generate
        cargo-leptos
        cargo-tauri
        cheese
        clamav
        clang_20
        clangStdenv
        cl-wordle
        cni-plugins
        containerd
        cosmic-applibrary
        cosmic-bg
        cosmic-comp
        cosmic-design-demo
        cosmic-edit
        cosmic-ext-applet-caffeine
        cosmic-ext-applet-external-monitor-brightness
        cosmic-ext-applet-minimon
        cosmic-ext-applet-privacy-indicator
        cosmic-ext-calculator
        cosmic-ext-ctl
        cosmic-ext-tweaks
        cosmic-files
        cosmic-greeter
        cosmic-icons
        cosmic-idle
        cosmic-launcher
        cosmic-notifications
        cosmic-osd
        cosmic-panel
        cosmic-player
        cosmic-protocols
        cosmic-randr
        cosmic-reader
        cosmic-screenshot
        cosmic-session
        cosmic-store
        cosmic-term
        cosmic-wallpapers
        cosmic-workspaces-epoch
        cowsay
        cri-o
        cryptsetup
        cups
        deja-dup
        delta
        dhall
        dhall-bash
        dhall-docs
        dhall-json
        dhall-lsp-server
        dhall-nix
        dhall-nixpkgs
        dhallPackages.dhall-kubernetes
        dhallPackages.Prelude
        dhall-yaml
        direnv
        distrobox
        doas
        docker
        dosfstools
        dotacatFast.packages.${system}.default
        dust
        e2fsprogs
        efibootmgr
        efitools
        efivar
        ente-desktop
        esbuild
        eza
        fastfetch
        fd
        ffmpeg_8-full
        file
        findutils
        firmware-updater
        fish
        fishPlugins.bass.src
        fishPlugins.foreign-env.src
        fishPlugins.grc.src
        fortune
        furmark
        fwupd-efi
        fzf
        gdk-pixbuf
        gh
        git-cliff
        git-filter-repo
        gitFull
        glib
        glmark2
        gobject-introspection
        graphviz
        grc
        grex
        grub2_efi
        gst_all_1.gstreamer
        gtk3
        gtkimageview
        gucharmap
        harfbuzz
        haskellPackages.dhall-openapi
        haskellPackages.dhall-toml
        haskellPackages.dhall-yaml
        hunspell
        hunspellDicts.en-us
        hyperfine
        intel-gpu-tools
        jdk
        jq
        jqp
        kernel-hardening-checker
        kind
        kitty
        kitty-img
        kitty-themes
        kompose
        kubectl
        kubernetes-helm
        libcanberra-gtk3
        (lib.hiPrio xwayland)
        libreoffice-fresh
        librewolf
        librsvg
        libsoup_3
        lld_20
        llvmPackages_20.clangUseLLVM
        lshw
        lsof
        lvm2
        mdadm
        mdcat
        mesa-demos
        microsoft-edge
        mullvad
        mullvad-compass
        mullvad-vpn
        nerdctl
        nerd-fonts.fira-code
        nerd-fonts.fira-mono
        networkmanager-iodine
        networkmanager-openvpn
        networkmanager-vpnc
        nftables
        nixd
        nix-index
        nix-prefetch-git
        nodejs
        nvim-pkg
        nvme-cli
        nvtopPackages.intel
        ollama-cuda
        openssl
        openssl.dev
        pandoc
        pango
        parted
        patool
        pciutils
        pineapple-pictures
        pkg-config
        plocate
        podman
        podman-compose
        podman-desktop
        psmisc
        pwgen
        ripgrep
        ripgrep-all
        rootlesskit
        seahorse
        signal-desktop
        simple-scan
        slirp4netns
        sqlite
        starship
        sysstat
        tailwindcss
        tealdeer
        tinyxxd
        tldr
        tmux
        tree
        tree-sitter
        trunk
        unzip
        usbutils
        uv
        viu
        vulkan-tools
        vulnix
        wayland-utils
        webkitgtk_4_1
        wget
        wine64
        winetricks
        wineWow64Packages.staging
        wineWow64Packages.waylandFull
        wireguard-tools
        wl-clipboard-rs
        wordbook
        xbindkeys
        xbindkeys-config
        xdg-desktop-portal-cosmic
        yaru-theme
        zed-editor
        zellij
        zoom-us
    ];
    wrapped-portal = wrapped-portal;
}
