# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "thunderbolt" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1db27bbc-1664-4514-af39-eb5b4c33c42b";
      fsType = "f2fs";
    };

  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/5ff6ab3a-cc58-4aff-a8bb-385158b232f9";
      fsType = "f2fs";
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/3b4706b4-cdbc-4a56-8dc2-2593997e3202";
      fsType = "f2fs";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/f7735ca8-86f4-4ac8-b2aa-7d54c577d0bf";
      fsType = "f2fs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/f2a36823-f7f9-4219-bab9-56abf6ef42a9";
      fsType = "ext4";
    };

  fileSystems."/boot/EFI" =
    { device = "/dev/disk/by-uuid/3D46-5D16";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/secrets" =
    { device = "/dev/disk/by-uuid/f0d0cb95-b5d4-4ecf-84e5-44ad9144f04b";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."secrets_crypt".device = "/dev/disk/by-uuid/7957c102-099b-403c-b15e-487e5c3cc052";

  swapDevices =
    [ { device = "/dev/disk/by-uuid/1bc7a795-732b-4115-8f65-d8a3d87863a1"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp17s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp16s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
